---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-col-taxa
  labels:
    app: etl-col-taxa
spec:
  template:
    metadata:
      name: etl-col-taxa
      labels:
        app: etl-col-taxa
    spec:
      restartPolicy: Never
      containers:
      - name: etl-col-taxa
        image: naturalis/nba-etl:V2.19-a5a48fe
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
        - "-c"
        - >
          set -x
          && sed -i "s/#test_genera.*/$TEST_GENERA/g" /payload/software/sh/include.sh
          && sed -i "s/truncate=true/truncate=false/g" /payload/software/sh/include.sh
          && wget -q https://dl.minio.io/client/mc/release/linux-amd64/mc
          && chmod +x mc
          && cp -fr /mc /mcwriteable
          && ./mc --config-dir /mcwriteable cp s3-nba-brondata/brondata-col/col-2018-04-30.tar.gz /payload/data/col
          && tar -xf /payload/data/col/col-2018-04-30.tar.gz -C /payload/data/col  
          && ./mc --config-dir /mcwriteable cp s3-nba-brondata/brondata-medialib/medialib-2019-05-27.tar.gz /payload/data/medialib
          && tar -xf /payload/data/medialib/medialib-2019-05-27.tar.gz -C /payload/data/medialib
          && ./col-import ; result=$?
          && gzip /payload/software/log/*.log
          && ./mc --config-dir /mcwriteable cp /payload/software/log/*.gz s3-nba-brondata/import-logs/2019-06-06/$(date +'%Y.%m.%d-%H.%M.%S')-col-taxa.log.gz
          && exit $result
        env:
        - name: "LOG_LEVEL"
          value: "INFO"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        volumeMounts:
        - name: logdir
          mountPath: /payload/software/log
        - name: datadir
          mountPath: /payload/data/col
        - name: mediadir
          mountPath: /payload/data/medialib
        - name: etl-nba-properties
          mountPath: /payload/software/conf/nba.properties
          subPath: nba.properties
        - name: etl-log4j2-xml
          mountPath: /payload/software/conf/log4j2.xml
          subPath: log4j2.xml
        - name: mc-s3-nba-brondata-config
          mountPath: /mc
      volumes:
      - name: datadir
        emptyDir: {}
      - name: mediadir
        emptyDir: {}
      - name: logdir
        emptyDir: {}
      - name: etl-nba-properties
        configMap:
          name: etl.nba.properties
      - name: etl-log4j2-xml
        configMap:
          name: etl.log4j2.xml
      - name: mc-s3-nba-brondata-config
        configMap:
          name: mc-s3-nba-brondata-config

