---
- hosts: all
  gather_facts: false
  tasks:

  - name: set date
    shell: date +'%Y-%m-%d'
    register: current_date
    run_once: true
    delegate_to: localhost
    changed_when: false

  - name: make dir sturcture
    file:
      state: directory
      path: "{{jobs_dir}}/{{group_names[0]|quote}}"
    delegate_to: localhost

  - name: write template
    template:
      src: templates/{{template_file}}
      dest: "{{jobs_dir}}/{{group_names[0]}}/{{inventory_hostname}}.yml"
    delegate_to: localhost

  - name: debug
    debug:
      msg: "{{ hostvars['brahms-l6-specimens']['s3_file'] }}"
    tags:
      - vars
    delegate_to: localhost
