---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-col-nullify
  labels:
    app: etl-col-nullify
spec:
  template:
    metadata:
      name: etl-col-nullify
      labels:
        app: etl-col-nullify
    spec:
      restartPolicy: Never
      containers:
      - name: etl-col-nullify
        image: naturalis/nba-etl:V2.11.2-5a9d0f4
        env:
        - name: "ES_DNS"
          value: "elasticsearch"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        - name: "AUTO_IMPORT"
          value: "TRUE"
        - name: "ENABLE_FILEBEAT"
          value: "FALSE"
        - name: "DEFAULT_SHARDS"
          value: "6"
        - name: "NUM_REPLICAS"
          value: "0"
        - name: "REPOS"
          value: "nba-brondata-medialib:2017-07"
        - name: "IMPORT_COMMAND"
          value: "./col-nullify"
        imagePullPolicy: Always
        volumeMounts:
        - name: nfs-pvc
          mountPath: "/payload/software/log"
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfslog
