---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-xc-multimedia
  labels:
    app: etl-xc-multimedia
spec:
  template:
    metadata:
      name: etl-xc-multimedia
      labels:
        app: etl-xc-multimedia
    spec:
      restartPolicy: Never
      containers:
      - name: etl-xc-multimedia
        image: naturalis/nba-etl:V2.18_dev_ES5.6.13-a301355
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args:
        - "-c"
        - >
          set -x
          && sed -i "s/#test_genera.*/$TEST_GENERA/g" /payload/software/sh/include.sh
          && sed -i "s/truncate=true/truncate=false/g" /payload/software/sh/include.sh
          && wget -q https://dl.minio.io/client/mc/release/linux-amd64/mc
          && chmod +x mc
          && ./mc --config-folder /mc cp s3-nba-brondata/brondata-xc/xc-multimedia-2018-11-02.tar.gz /payload/data/json/multimedia
          && tar -xf /payload/data/json/multimedia/xc-multimedia-2018-11-02.tar.gz -C /payload/data/json/multimedia  
          && ./mc --config-folder /mc cp s3-nba-brondata/brondata-medialib/medialib-2018-11-09.tar.gz /payload/data/medialib
          && tar -xf /payload/data/medialib/medialib-2018-11-09.tar.gz -C /payload/data/medialib
          && ./json-import multimedia ; result=$?
          && gzip /payload/software/log/*.log
          && ./mc --config-folder /mc cp /payload/software/log/*.gz s3-nba-brondata/import-logs/2018-11-26/$(date +'%Y.%m.%d-%H.%M.%S')-xc-multimedia.log.gz
          && exit $result
        env:
        - name: "LOG_LEVEL"
          value: "INFO"
        - name: "TEST_GENERA"
          value: "#test_genera=malus,parus,larus,bombus,rhododendron,felix,tulipa,rosa,canis,passer,trientalis"
        volumeMounts:
        - name: logdir
          mountPath: /payload/software/log
        - name: datadir
          mountPath: /payload/data/json/multimedia
        - name: mediadir
          mountPath: /payload/data/medialib
        - name: etl-nba-properties
          mountPath: /payload/software/conf/nba.properties
          subPath: nba.properties
        - name: etl-log4j2-xml
          mountPath: /payload/software/conf/log4j2.xml
          subPath: log4j2.xml
        - name: mc-s3-nba-brondata-config
          mountPath: /mc
      volumes:
      - name: datadir
        emptyDir: {}
      - name: mediadir
        emptyDir: {}
      - name: logdir
        emptyDir: {}
      - name: etl-nba-properties
        configMap:
          name: etl.nba.properties
      - name: etl-log4j2-xml
        configMap:
          name: etl.log4j2.xml
      - name: mc-s3-nba-brondata-config
        configMap:
          name: mc-s3-nba-brondata-config

