---
apiVersion: batch/v1
kind: Job
metadata:
  name: download-col
  labels:
    app: download-col
spec:
  template:
    metadata:
      name: download-col
      labels:
        app: download-col
    spec:
      restartPolicy: Never
      containers:
      - name: download-col
        image: alpine
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          apk add --no-cache git
          && git clone https://github.com/naturalis/nba-brondata-col /data/col -b $BRONDATA_TAG
          && (cd /data/col ; ./uncompress.sh)
      env:
        - name: "BRONDATA_TAG"
          value: "2017-07"
      volumeMounts:
        - name: sourcedata-pvc
          mountPath: /data
    volumes:
      - name: sourcedata-pvc
        persistentVolumeClaim:
          claimName: sourcedata

