apiVersion: v1
data:
  nba.properties: |
    elasticsearch.cluster.name=nba-cluster
    elasticsearch.transportaddress.host=elasticsearch-data
    elasticsearch.transportaddress.port=9300
    elasticsearch.index.default.shards=16
    elasticsearch.index.default.replicas=0
    elasticsearch.index.0.name=specimen
    elasticsearch.index.0.types=Specimen
    elasticsearch.index.1.name=taxon
    elasticsearch.index.1.types=Taxon
    elasticsearch.index.2.name=multimedia
    elasticsearch.index.2.types=MultiMediaObject
    elasticsearch.index.3.name=geoareas
    elasticsearch.index.3.types=GeoArea
    elasticsearch.index.3.shards=1
    nba.etl.install.dir=/payload/software
    crs.data.dir=/payload/data/crs
    col.data.dir=/payload/data/col
    brahms.data.dir=/payload/data/brahms
    nsr.data.dir=/payload/data/nsr
    geo.data.dir=/payload/data/geo
    ndff.data.dir=/payload/data/ndff
    medialib.data.dir=/payload/data/medialib
    json.data.dir=/payload/data/json
    col.year=2019
    purl.baseurl=http://data.biodiversitydata.nl
kind: ConfigMap
metadata:
  name: etl.nba.properties

