---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfslog
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi

