---
apiVersion: batch/v1
kind: Job
metadata:
  name: etl-add-multimedia-to-specimens
  labels:
    app: etl-add-multimedia-to-specimens
spec:
  template:
    metadata:
      name: etl-add-multimedia-to-specimens
      labels:
        app: etl-add-multimedia-to-specimens
    spec:
      restartPolicy: Never
      containers:
      - name: etl-add-multimedia-to-specimens
        image: naturalis/nba-etl:V2.19-a5a48fe
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args:
        - "-c"
        - >
          set -x
          && sed -i 's/read_batch_size=1000/read_batch_size=500/g' add-multimedia-to-specimens
          && wget -q https://dl.minio.io/client/mc/release/linux-amd64/mc
          && chmod +x mc
          && cp -fr /mc /mcwriteable
          && ./add-multimedia-to-specimens ; result=$?
          && gzip /payload/software/log/*.log
          && ./mc --config-dir /mcwriteable cp /payload/software/log/*.gz s3-nba-brondata/import-logs/2019-06-13/$(date +'%Y.%m.%d-%H.%M.%S')-add-multimedia-to-specimens.log.gz
          && exit $result
        volumeMounts:
        - name: logdir
          mountPath: /payload/software/log
        - name: etl-nba-properties
          mountPath: /payload/software/conf/nba.properties
          subPath: nba.properties
        - name: etl-log4j2-xml
          mountPath: /payload/software/conf/log4j2.xml
          subPath: log4j2.xml
        - name: mc-s3-nba-brondata-config
          mountPath: /mc
      volumes:
      - name: logdir
        emptyDir: {}
      - name: etl-nba-properties
        configMap:
          name: etl.nba.properties
      - name: etl-log4j2-xml
        configMap:
          name: etl.log4j2.xml
      - name: mc-s3-nba-brondata-config
        configMap:
          name: mc-s3-nba-brondata-config
